#!/encs/bin/bash

echo "-----------------Installing python-tk ----------------"
sudo apt install python-tk

echo "-----------------Installing graphviz and pip for python2 ----------------"
sudo apt-get install graphviz libgraphviz-dev pkg-config python-pip

echo "-----------------Installing pygraphviz ----------------"
sudo apt-get install -y python-pygraphviz

echo "-----------------Installing NumPy -----------------"
pip install --user numpy

echo "-----------------Installing Pandas -----------------"
pip install --user pandas

echo "-----------------Installing MatPlotlib ----------------"
pip install --user matplotlib

echo "-----------------Installing NetworkX ----------------"
pip install --user networkx

echo "-----------------Installing easygui ----------------"
pip install --user easygui

echo "-----------------Installing pptree ----------------"
pip install --user pptree






